      - name: Configurar JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      # PASO CLAVE: Instala el NDK para compilar OpenCV y tu código C++
      - name: Setup Android NDK
        uses: nandroid/setup-ndk@v3
        with:
          ndk-version: r25c # Versión recomendada para compatibilidad

      - name: Compilar APK
        run: |
          chmod +x gradlew
          ./gradlew assembleDebug --no-daemon
